import io
import json
from datetime import datetime
from typing import Any, Iterable


def _safe_text(v: Any) -> str:
    if v is None:
        return ""
    return str(v)

def _parse_details(details_raw: Any) -> dict[str, Any]:
    if isinstance(details_raw, dict):
        return details_raw
    if isinstance(details_raw, str) and details_raw.strip():
        try:
            parsed = json.loads(details_raw)
            return parsed if isinstance(parsed, dict) else {}
        except Exception:
            return {}
    return {}


def _pdf_theme():
    from reportlab.lib import colors
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet

    base = getSampleStyleSheet()
    primary = colors.HexColor("#0B1F3A")
    accent = colors.HexColor("#2563EB")
    success = colors.HexColor("#16A34A")
    danger = colors.HexColor("#DC2626")
    muted = colors.HexColor("#64748B")
    border = colors.HexColor("#E2E8F0")
    bg_soft = colors.HexColor("#F8FAFC")

    styles = {
        "cover_title": ParagraphStyle(
            name="nm_cover_title",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=28,
            leading=34,
            textColor=primary,
            spaceAfter=10,
        ),
        "cover_sub": ParagraphStyle(
            name="nm_cover_sub",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=12,
            leading=16,
            textColor=muted,
            spaceAfter=18,
        ),
        "title": ParagraphStyle(
            name="nm_title",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=24,
            textColor=primary,
            spaceAfter=8,
        ),
        "h1": ParagraphStyle(
            name="nm_h1",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=15,
            textColor=primary,
            spaceBefore=10,
            spaceAfter=6,
        ),
        "sub": ParagraphStyle(
            name="nm_sub",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=13,
            textColor=muted,
            spaceAfter=8,
        ),
        "body": ParagraphStyle(
            name="nm_body",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=primary,
            wordWrap="CJK",
        ),
        "small": ParagraphStyle(
            name="nm_small",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=muted,
            wordWrap="CJK",
        ),
        "badge": ParagraphStyle(
            name="nm_badge",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=colors.white,
            alignment=1,
        ),
    }

    return {
        "colors": {
            "primary": primary,
            "accent": accent,
            "success": success,
            "danger": danger,
            "muted": muted,
            "border": border,
            "bg_soft": bg_soft,
        },
        "styles": styles,
    }


def _draw_page_header_footer(canvas, doc, title: str):
    from reportlab.lib.units import mm

    theme = _pdf_theme()
    primary = theme["colors"]["primary"]
    muted = theme["colors"]["muted"]
    border = theme["colors"]["border"]

    canvas.saveState()

    w, h = doc.pagesize
    top = h - doc.topMargin + 8 * mm
    left = doc.leftMargin
    right = w - doc.rightMargin

    canvas.setLineWidth(0.5)
    canvas.setStrokeColor(border)
    canvas.line(left, top - 12 * mm, right, top - 12 * mm)

    canvas.setFillColor(primary)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(left, top - 8 * mm, title)

    canvas.setFillColor(muted)
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(right, top - 8 * mm, f"Page {canvas.getPageNumber()}")

    canvas.setFillColor(muted)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(left, doc.bottomMargin - 10, "Generated by NetManager")
    canvas.drawRightString(right, doc.bottomMargin - 10, datetime.now().isoformat(timespec="seconds"))

    canvas.restoreState()


def _make_kpi_cards(rows: list[tuple[str, str, str]], total_width: float):
    from reportlab.platypus import Paragraph, Table, TableStyle
    from reportlab.lib import colors

    theme = _pdf_theme()
    border = theme["colors"]["border"]
    bg_soft = theme["colors"]["bg_soft"]
    primary = theme["colors"]["primary"]
    muted = theme["colors"]["muted"]
    body = theme["styles"]["body"]

    cells = []
    for title, value, subtitle in rows:
        cells.append(
            Paragraph(
                f"<font color='{muted.hexval()}' size='8'>{_safe_text(title)}</font><br/>"
                f"<font color='{primary.hexval()}' size='15'><b>{_safe_text(value)}</b></font><br/>"
                f"<font color='{muted.hexval()}' size='8'>{_safe_text(subtitle)}</font>",
                body,
            )
        )

    col_width = total_width / max(1, len(cells))
    table = Table([cells], colWidths=[col_width] * len(cells))
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), bg_soft),
                ("BOX", (0, 0), (-1, -1), 0.6, border),
                ("INNERGRID", (0, 0), (-1, -1), 0.6, border),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    return table


def _draw_cover_background(canvas, doc):
    from reportlab.lib import colors
    from reportlab.lib.units import mm

    theme = _pdf_theme()
    accent = theme["colors"]["accent"]
    bg_soft = theme["colors"]["bg_soft"]
    border = theme["colors"]["border"]

    canvas.saveState()
    w, h = doc.pagesize
    canvas.setFillColor(bg_soft)
    canvas.rect(0, 0, w, h, stroke=0, fill=1)
    canvas.setFillColor(accent)
    canvas.rect(0, h - 28 * mm, w, 28 * mm, stroke=0, fill=1)
    canvas.setStrokeColor(border)
    canvas.setLineWidth(1)
    canvas.rect(doc.leftMargin - 6 * mm, doc.bottomMargin - 6 * mm, doc.width + 12 * mm, doc.height + 12 * mm, stroke=1, fill=0)
    canvas.restoreState()


def _toc_flowable():
    from reportlab.platypus import Paragraph
    from reportlab.platypus.tableofcontents import TableOfContents

    theme = _pdf_theme()
    styles = theme["styles"]

    toc = TableOfContents()
    toc.levelStyles = [
        styles["body"],
    ]
    return Paragraph("Contents", styles["title"]), toc


def _build_doc(buf: io.BytesIO, pagesize, doc_title: str, header_title: str, *, left_margin, right_margin, top_margin, bottom_margin):
    from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate

    class _Doc(BaseDocTemplate):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._header_title = header_title

        def afterFlowable(self, flowable):
            try:
                from reportlab.platypus import Paragraph
            except Exception:
                return
            if not isinstance(flowable, Paragraph):
                return
            style_name = getattr(getattr(flowable, "style", None), "name", "")
            if style_name != "nm_h1":
                return
            text = getattr(flowable, "getPlainText", lambda: "")()
            if text:
                self.notify("TOCEntry", (0, text, self.page))

    doc = _Doc(
        buf,
        pagesize=pagesize,
        title=doc_title,
        leftMargin=left_margin,
        rightMargin=right_margin,
        topMargin=top_margin,
        bottomMargin=bottom_margin,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="F")
    doc.addPageTemplates(
        [
            PageTemplate(id="cover", frames=[frame], onPage=lambda c, d: _draw_cover_background(c, d)),
            PageTemplate(id="body", frames=[frame], onPage=lambda c, d: _draw_page_header_footer(c, d, header_title)),
        ]
    )
    return doc


def build_inventory_xlsx(device_name: str, items: Iterable[Any]) -> bytes:
    from openpyxl import Workbook
    from openpyxl.styles import Font

    wb = Workbook()
    ws = wb.active
    ws.title = "Inventory"

    header = [
        "ent_physical_index",
        "parent_index",
        "class_id",
        "class_name",
        "name",
        "description",
        "model_name",
        "serial_number",
        "mfg_name",
        "hardware_rev",
        "firmware_rev",
        "software_rev",
        "is_fru",
        "last_seen",
    ]
    ws.append(header)
    for cell in ws[1]:
        cell.font = Font(bold=True)

    for i in items:
        ws.append(
            [
                getattr(i, "ent_physical_index", None),
                getattr(i, "parent_index", None),
                getattr(i, "class_id", None),
                _safe_text(getattr(i, "class_name", None)),
                _safe_text(getattr(i, "name", None)),
                _safe_text(getattr(i, "description", None)),
                _safe_text(getattr(i, "model_name", None)),
                _safe_text(getattr(i, "serial_number", None)),
                _safe_text(getattr(i, "mfg_name", None)),
                _safe_text(getattr(i, "hardware_rev", None)),
                _safe_text(getattr(i, "firmware_rev", None)),
                _safe_text(getattr(i, "software_rev", None)),
                _safe_text(getattr(i, "is_fru", None)),
                _safe_text(getattr(i, "last_seen", None)),
            ]
        )

    bio = io.BytesIO()
    wb.save(bio)
    return bio.getvalue()


def build_compliance_xlsx(reports: Iterable[dict[str, Any]]) -> bytes:
    from openpyxl import Workbook
    from openpyxl.styles import Font

    wb = Workbook()
    ws = wb.active
    ws.title = "Summary"

    summary_header = ["device_id", "device_name", "status", "score", "last_checked"]
    ws.append(summary_header)
    for cell in ws[1]:
        cell.font = Font(bold=True)

    for r in reports:
        ws.append(
            [
                r.get("device_id"),
                _safe_text(r.get("device_name")),
                _safe_text(r.get("status")),
                r.get("score"),
                _safe_text(r.get("last_checked")),
            ]
        )

    ws2 = wb.create_sheet("Details")
    details_header = ["device_id", "standard", "total", "passed", "score", "violations"]
    ws2.append(details_header)
    for cell in ws2[1]:
        cell.font = Font(bold=True)

    for r in reports:
        details_raw = r.get("details")
        details = {}
        if isinstance(details_raw, dict):
            details = details_raw
        elif isinstance(details_raw, str) and details_raw.strip():
            try:
                details = json.loads(details_raw)
            except Exception:
                details = {}

        if not details:
            continue

        for std_name, d in details.items():
            ws2.append(
                [
                    r.get("device_id"),
                    _safe_text(std_name),
                    d.get("total"),
                    d.get("passed"),
                    d.get("score"),
                    _safe_text(d.get("violations")),
                ]
            )

    bio = io.BytesIO()
    wb.save(bio)
    return bio.getvalue()


def build_inventory_pdf(device_name: str, items: Iterable[Any]) -> bytes:
    from collections import Counter

    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, Spacer, Table, TableStyle, PageBreak, NextPageTemplate, KeepTogether

    buf = io.BytesIO()
    doc = _build_doc(
        buf,
        pagesize=landscape(A4),
        doc_title=f"Inventory - {device_name}",
        header_title="Inventory Report",
        left_margin=16 * mm,
        right_margin=16 * mm,
        top_margin=18 * mm,
        bottom_margin=16 * mm,
    )
    theme = _pdf_theme()
    styles = theme["styles"]
    border = theme["colors"]["border"]
    bg_soft = theme["colors"]["bg_soft"]
    primary = theme["colors"]["primary"]

    items_list = list(items or [])
    total = len(items_list)
    models = set(_safe_text(getattr(i, "model_name", "")).strip() for i in items_list if _safe_text(getattr(i, "model_name", "")).strip())
    serials = set(_safe_text(getattr(i, "serial_number", "")).strip() for i in items_list if _safe_text(getattr(i, "serial_number", "")).strip())
    class_counts = Counter(_safe_text(getattr(i, "class_name", "")).strip() or "Unknown" for i in items_list)

    elements = []
    elements.append(NextPageTemplate("body"))
    elements.append(Paragraph("Inventory Report", styles["cover_title"]))
    elements.append(Paragraph(f"Device: <b>{_safe_text(device_name)}</b>", styles["cover_sub"]))
    elements.append(
        _make_kpi_cards(
            [
                ("TOTAL ITEMS", f"{total}", "ENTITY-MIB entries"),
                ("UNIQUE MODELS", f"{len(models)}", "Detected hardware models"),
                ("SERIALS", f"{len(serials)}", "Unique serial numbers"),
            ],
            doc.width,
        )
    )
    elements.append(Spacer(1, 14))
    elements.append(PageBreak())

    toc_title, toc = _toc_flowable()
    elements.append(toc_title)
    elements.append(Spacer(1, 6))
    elements.append(toc)
    elements.append(PageBreak())

    top_classes = sorted(class_counts.items(), key=lambda x: (-x[1], x[0]))[:12]
    if top_classes:
        elements.append(Paragraph("Inventory Summary", styles["h1"]))
        summary_data = [["Class", "Count"]]
        for k, v in top_classes:
            summary_data.append([Paragraph(_safe_text(k), styles["body"]), str(v)])
        summary_table = Table(summary_data, colWidths=[doc.width * 0.7, doc.width * 0.3], repeatRows=1)
        summary_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), primary),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.4, border),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [bg_soft, colors.white]),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        elements.append(summary_table)
        elements.append(PageBreak())

    elements.append(Paragraph("Inventory Details", styles["h1"]))

    header = ["Index", "Parent", "Class", "Name", "Model", "Serial", "HW", "FW", "SW", "Last Seen"]
    data = [header]
    for i in items_list:
        data.append(
            [
                _safe_text(getattr(i, "ent_physical_index", "")),
                _safe_text(getattr(i, "parent_index", "")),
                Paragraph(_safe_text(getattr(i, "class_name", "")), styles["body"]),
                Paragraph(_safe_text(getattr(i, "name", "")), styles["body"]),
                Paragraph(_safe_text(getattr(i, "model_name", "")), styles["body"]),
                Paragraph(_safe_text(getattr(i, "serial_number", "")), styles["body"]),
                _safe_text(getattr(i, "hardware_rev", "")),
                _safe_text(getattr(i, "firmware_rev", "")),
                _safe_text(getattr(i, "software_rev", "")),
                _safe_text(getattr(i, "last_seen", "")),
            ]
        )

    col_widths = [
        doc.width * 0.06,
        doc.width * 0.06,
        doc.width * 0.10,
        doc.width * 0.18,
        doc.width * 0.14,
        doc.width * 0.14,
        doc.width * 0.06,
        doc.width * 0.06,
        doc.width * 0.06,
        doc.width * 0.14,
    ]
    table = Table(data, repeatRows=1, colWidths=col_widths)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), primary),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("GRID", (0, 0), (-1, -1), 0.35, border),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, bg_soft]),
                ("FONTSIZE", (0, 1), (-1, -1), 8),
                ("TEXTCOLOR", (0, 1), (-1, -1), primary),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    elements.append(KeepTogether([table]))
    doc.multiBuild(elements)
    return buf.getvalue()


def build_compliance_pdf(reports: Iterable[dict[str, Any]]) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, Spacer, Table, TableStyle, PageBreak, NextPageTemplate, KeepTogether

    buf = io.BytesIO()
    doc = _build_doc(
        buf,
        pagesize=A4,
        doc_title="Compliance Reports",
        header_title="Compliance Report",
        left_margin=16 * mm,
        right_margin=16 * mm,
        top_margin=18 * mm,
        bottom_margin=16 * mm,
    )
    theme = _pdf_theme()
    styles = theme["styles"]
    primary = theme["colors"]["primary"]
    border = theme["colors"]["border"]
    bg_soft = theme["colors"]["bg_soft"]
    success = theme["colors"]["success"]
    danger = theme["colors"]["danger"]
    muted = theme["colors"]["muted"]

    reports_list = list(reports or [])
    total = len(reports_list)
    compliant = sum(1 for r in reports_list if str(r.get("status") or "").lower() == "compliant")
    violations = sum(1 for r in reports_list if str(r.get("status") or "").lower() == "violation")
    avg_score = 0.0
    if total:
        scores = []
        for r in reports_list:
            try:
                scores.append(float(r.get("score")))
            except Exception:
                pass
        avg_score = sum(scores) / len(scores) if scores else 0.0

    elements = []
    elements.append(NextPageTemplate("body"))
    elements.append(Paragraph("Compliance Report", styles["cover_title"]))
    elements.append(Paragraph("Rule-based compliance scan results and drift indicators.", styles["cover_sub"]))
    elements.append(
        _make_kpi_cards(
            [
                ("DEVICES", f"{total}", "Reports available"),
                ("COMPLIANT", f"{compliant}", "No violations detected"),
                ("VIOLATIONS", f"{violations}", "Action required"),
                ("AVG SCORE", f"{avg_score:.1f}%", "Overall posture"),
            ],
            doc.width,
        )
    )
    elements.append(Spacer(1, 14))
    elements.append(PageBreak())

    toc_title, toc = _toc_flowable()
    elements.append(toc_title)
    elements.append(Spacer(1, 6))
    elements.append(toc)
    elements.append(PageBreak())

    elements.append(Paragraph("Summary", styles["h1"]))

    data = [["Device", "Status", "Score", "Last Checked"]]
    for r in sorted(reports_list, key=lambda x: (_safe_text(x.get("device_name") or x.get("device_id")).lower())):
        status = _safe_text(r.get("status")).lower()
        status_label = status.upper() if status else "UNKNOWN"
        data.append(
            [
                Paragraph(_safe_text(r.get("device_name") or r.get("device_id")), styles["body"]),
                Paragraph(status_label, styles["body"]),
                _safe_text(r.get("score")),
                _safe_text(r.get("last_checked")),
            ]
        )

    table = Table(data, repeatRows=1, colWidths=[doc.width * 0.40, doc.width * 0.18, doc.width * 0.14, doc.width * 0.28])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), primary),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.35, border),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, bg_soft]),
                ("FONTSIZE", (0, 1), (-1, -1), 9),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )

    for idx in range(1, len(data)):
        status = str(getattr(data[idx][1], "getPlainText", lambda: data[idx][1])() or "").lower()
        if status == "compliant":
            table.setStyle(
                TableStyle(
                    [
                        ("TEXTCOLOR", (1, idx), (1, idx), success),
                        ("FONTNAME", (1, idx), (1, idx), "Helvetica-Bold"),
                        ("BACKGROUND", (1, idx), (1, idx), colors.HexColor("#ECFDF5")),
                    ]
                )
            )
        elif status == "violation":
            table.setStyle(
                TableStyle(
                    [
                        ("TEXTCOLOR", (1, idx), (1, idx), danger),
                        ("FONTNAME", (1, idx), (1, idx), "Helvetica-Bold"),
                        ("BACKGROUND", (1, idx), (1, idx), colors.HexColor("#FEF2F2")),
                    ]
                )
            )

    elements.append(table)

    def _extract_violation_rows(details: dict[str, Any]) -> list[list[str]]:
        out = []
        for std_name, d in (details or {}).items():
            violations_list = d.get("violations") if isinstance(d, dict) else None
            if not isinstance(violations_list, list):
                continue
            for v in violations_list:
                if not isinstance(v, dict):
                    continue
                out.append(
                    [
                        _safe_text(std_name),
                        _safe_text(v.get("rule")),
                        _safe_text(v.get("severity")),
                        _safe_text(v.get("remediation")),
                    ]
                )
        return out

    violators = [r for r in reports_list if str(r.get("status") or "").lower() == "violation"]
    if violators:
        elements.append(PageBreak())
        elements.append(Paragraph("Findings (Top Violations)", styles["h1"]))
        for r in sorted(violators, key=lambda x: (_safe_text(x.get("device_name") or x.get("device_id")).lower())):
            dev_name = _safe_text(r.get("device_name") or r.get("device_id"))
            elements.append(Paragraph(f"<b>{dev_name}</b>", styles["body"]))
            details = _parse_details(r.get("details"))
            rows = _extract_violation_rows(details)[:20]
            if not rows:
                elements.append(Paragraph("No detailed violations available.", styles["small"]))
                elements.append(Spacer(1, 6))
                continue
            vdata = [["Standard", "Rule", "Severity", "Remediation"]] + rows
            vtable = Table(vdata, repeatRows=1, colWidths=[doc.width * 0.18, doc.width * 0.32, doc.width * 0.12, doc.width * 0.38])
            vtable.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), primary),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("GRID", (0, 0), (-1, -1), 0.35, border),
                        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, bg_soft]),
                        ("FONTSIZE", (0, 1), (-1, -1), 8),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 6),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                        ("TOPPADDING", (0, 0), (-1, -1), 5),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ]
                )
            )
            for ridx in range(1, len(vdata)):
                sev = str(vdata[ridx][2] or "").strip().lower()
                if sev in {"critical", "high"}:
                    vtable.setStyle(TableStyle([("BACKGROUND", (2, ridx), (2, ridx), colors.HexColor("#FEE2E2")), ("TEXTCOLOR", (2, ridx), (2, ridx), danger), ("FONTNAME", (2, ridx), (2, ridx), "Helvetica-Bold")]))
                elif sev in {"warning", "medium"}:
                    vtable.setStyle(TableStyle([("BACKGROUND", (2, ridx), (2, ridx), colors.HexColor("#FEF9C3")), ("TEXTCOLOR", (2, ridx), (2, ridx), colors.HexColor("#A16207")), ("FONTNAME", (2, ridx), (2, ridx), "Helvetica-Bold")]))
                elif sev in {"low", "info"}:
                    vtable.setStyle(TableStyle([("BACKGROUND", (2, ridx), (2, ridx), colors.HexColor("#E0F2FE")), ("TEXTCOLOR", (2, ridx), (2, ridx), colors.HexColor("#0369A1")), ("FONTNAME", (2, ridx), (2, ridx), "Helvetica-Bold")]))
            elements.append(KeepTogether([vtable]))
            elements.append(Spacer(1, 10))

    doc.multiBuild(elements)
    return buf.getvalue()
